from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Tuple

class DatabaseClient(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def execute(self, sql: str, params: Optional[tuple] = None) -> None: ...
    @abstractmethod
    def fetchone(self, sql: str, params: Optional[tuple] = None) -> Optional[tuple]: ...
    @abstractmethod
    def fetchall(self, sql: str, params: Optional[tuple] = None) -> List[tuple]: ...
    @abstractmethod
    def commit(self) -> None: ...
    @abstractmethod
    def rollback(self) -> None: ...

class SchemaRepository(ABC):
    @abstractmethod
    def drop_all(self) -> None: ...
    @abstractmethod
    def create_all(self) -> None: ...

class ResourceImporter(ABC):
    @abstractmethod
    def import_resources(self, json_file: str, incremental: bool = False) -> Dict[str, int]: ...